name: GoTestReport

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
    go-test-report:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.19

            - name: Test the application
              uses: brian-pickens/go-test-report@v1
              with:
                packages: "./..."
                reports-only: "false"
                summary: "true"
                GO111MODULE: "auto"