name: GoLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run golangci-lint
        run: |
          GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.1
          export GOBIN=$HOME/bin
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.1
          export PATH=$PATH:$GOBIN
          go golangci-lint run ./...
