name: GoLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check for Go file changes
        id: check_go_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.go$'; then
            echo "Go files modified or added, continuing with linting."
            echo "::set-output name=lint_go::true"
          else
            echo "No Go files modified or added, skipping linting."
          fi

      - name: Run golangci-lint
        run: |
          if [[ "${{ steps.check_go_changes.outputs.lint_go }}" == "true" ]]; then
            GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.1
            golangci-lint run ./...
          fi
